Repository fga-eps-mds/2021.1-Oraculo-Profile, pull requests merged in 2021-11, with the labels that each got.

#21 146 create department crud
  README.md
  package.json
  src/Controller/DepartmentController.js
  src/Controller/SectionController.js
  src/Controller/UserController.js
  src/Database/migrations/20210923004505-create-departments.js
  src/Database/migrations/20210925183750-create-sections.js
  src/Model/Department.js
  src/Model/Section.js
  src/routes.js
  tests/create-admin.js
  tests/index.test.js
Labels: EPS, MDS, FEATURE, MEDIUM

#22 feat: returns user name with user information fga-eps-mds/2021.1-Orac…
  src/Controller/UserController.js
Labels: MDS, FEATURE, EASY

#23 163 incluir retorno seções do usuario
  src/Controller/UserController.js
  src/routes.js
Labels: MDS, EASY

#24 150 change user endpoint
  README.md
  package.json
  src/Controller/UserController.js
  tests/create-admin.js
Labels: MDS, FEATURE, EASY

#25 165 improve edit user endpoint
  README.md
  src/Controller/UserController.js
  src/routes.js
  tests/index.test.js
Labels: MDS, FEATURE, MEDIUM

#26 163 incluir retorno seções do usuario
  README.md
  src/Controller/UserController.js
Labels: MDS, FEATURE, EASY

#27 186 unificacao secao departamento
  src/Controller/SectionController.js
  src/Controller/UserController.js
  src/Database/index.js
  src/Database/migrations/20210925183750-create-sections.js
  src/Database/migrations/20210925183758-create-user-sections.js
  src/Database/seeders/20211020021258-departments.js
  src/Database/seeders/20211020024954-sections.js
  src/Model/Section.js
  src/Model/User.js
  src/routes.js
  tests/create-admin.js
  tests/index.test.js
Labels: MDS, HARD
