Repository fga-eps-mds/2021.1-Oraculo-Profile, pull requests merged in 2021-09, with the labels that each got.

#1 #60 Configurar envio automático do arquivo do sonarcloud
  .github/workflows/release.yml
Labels: DEVOPS, EPS, DOCS

#6 fga-eps-mds/2021.1-Oraculo#41 registered users
  package.json
  src/Controller/UserController.js
  src/Utils/JWT.js
  src/index.js
  src/routes.js
  tests/index.test.js
Labels: MDS, FEATURE, MEDIUM

#2 #53 Configurar cobertura de testes nos microsserviços
  .gitignore
  package.json
  sonar-project.properties
Labels: DEVOPS, EPS

#7 #40 Criar contas de usuário com privilégios administrativos
  .github/workflows/sonarcloud.yml
  package.json
  prepare.sh
  src/Controller/UserController.js
  src/Database/index.js
  src/index.js
  src/routes.js
  tests/create-admin.js
  tests/index.test.js
Labels: MDS, FEATURE, MEDIUM

#8 #39 Criar níveis de acessos diferentes
  README.md
  sonar-project.properties
  src/Controller/UserController.js
  src/routes.js
  tests/index.test.js
Labels: MDS, FEATURE, MEDIUM
